name: Deploy Apache EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Deploy a EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🚀 Deploy iniciado"

            if [ ! -d "EjercicioEC2_aws_IngDvs" ]; then
              git clone https://github.com/dxminique/EjercicioEC2_aws_IngDvs.git
            fi

            cd EjercicioEC2_aws_IngDvs
            git fetch origin
            git reset --hard origin/main

            sudo cp index.html /var/www/html/index.html
            sudo systemctl restart httpd

            echo "✅ Deploy terminado"git add .